import json
import os
import tempfile
from typing import Optional, List

from fastapi import APIRouter, File, Form, HTTPException, UploadFile, Header, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.models.anamnesis import AnamnesisInput, AnalysisResponse
from app.services.clinical_ai import run_clinical_analysis
from app.database import get_db

router = APIRouter(prefix="/analysis", tags=["clinical-analysis"])


import re as _re
import logging as _logging
_log = _logging.getLogger(__name__)


def _strip_markdown(text: str) -> str:
    """Remove markdown symbols from AI replies before sending to client."""
    text = _re.sub(r'\*\*', '', text)                        # **bold**
    text = _re.sub(r'\*', '', text)                          # *italic*
    text = _re.sub(r'^#{1,6}\s+', '', text, flags=_re.M)    # ## headings
    text = _re.sub(r'`', '', text)                           # `code`
    text = _re.sub(r'^[–—]\s*$', '', text, flags=_re.M)     # lone em-dash lines
    text = _re.sub(r'\n{3,}', '\n\n', text)                  # max 2 newlines
    return text.strip()

from app.core.token_utils import deduct_token

# Max video size accepted: 200 MB
MAX_VIDEO_BYTES = 200 * 1024 * 1024

ALLOWED_VIDEO_TYPES = {
    "video/mp4", "video/quicktime", "video/x-msvideo",
    "video/x-matroska", "video/webm", "video/mpeg",
}


@router.post("", response_model=AnalysisResponse)
def create_analysis(
    anamnesis: AnamnesisInput,
    authorization: Optional[str] = Header(None),
    db: Session = Depends(get_db),
):
    """
    Run a Functional Behavioral Analysis (text-only anamnesis).

    Accepts the full anamnesis form, retrieves relevant knowledge from
    Qdrant, and returns a clinical ABC analysis generated by Claude
    Sonnet 4.6 with prompt caching active on the system prompt.
    Deducts 3 tokens from the authenticated user (requires login).
    Admins and collaborators are exempt from deduction.
    """
    deduct_token(authorization, db, amount=3.0, require_auth=True)
    try:
        return run_clinical_analysis(anamnesis)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/video", response_model=AnalysisResponse)
async def create_analysis_with_video(
    anamnesis_json: str = Form(..., description="Full AnamnesisInput serialised as JSON"),
    video: UploadFile = File(..., description="Video of the dog's behavior (MP4, MOV, AVI…)"),
    authorization: Optional[str] = Header(None),
    db: Session = Depends(get_db),
):
    """
    Run a Functional Behavioral Analysis with an attached video.

    The video is stored to a temporary file, key frames are extracted
    with OpenCV (or ffmpeg as fallback), and the frames are passed to
    Claude alongside the written anamnesis for multi-modal analysis.
    """
    # ── Deduct token (3 tokens, requires auth) ───────────────────────────────
    deduct_token(authorization, db, amount=3.0, require_auth=True)

    # ── Validate content type ────────────────────────────────────────────────
    ct = (video.content_type or "").lower()
    if ct and ct not in ALLOWED_VIDEO_TYPES:
        raise HTTPException(
            status_code=415,
            detail=f"Unsupported video format: {ct}. Use MP4, MOV, AVI or MKV.",
        )

    # ── Read & size-check the upload ─────────────────────────────────────────
    video_bytes = await video.read()
    if len(video_bytes) > MAX_VIDEO_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"Video too large ({len(video_bytes) // 1024 // 1024} MB). Max 200 MB.",
        )

    # ── Parse anamnesis ──────────────────────────────────────────────────────
    try:
        anamnesis_data = json.loads(anamnesis_json)
        anamnesis = AnamnesisInput(**anamnesis_data)
    except Exception as e:
        raise HTTPException(status_code=422, detail=f"Invalid anamnesis JSON: {e}")

    # ── Write video to temp file & extract frames ────────────────────────────
    suffix = os.path.splitext(video.filename or "video.mp4")[1] or ".mp4"
    tmp_path = None
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            tmp.write(video_bytes)
            tmp_path = tmp.name

        from app.services.video_processor import extract_frames
        try:
            frames = extract_frames(tmp_path)
        except RuntimeError as e:
            # Frame extraction failed — fall back to text-only analysis
            frames = []
            import logging
            logging.getLogger(__name__).warning(
                "Frame extraction failed, falling back to text-only: %s", e
            )

        return run_clinical_analysis(anamnesis, video_frames=frames or None)

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if tmp_path and os.path.exists(tmp_path):
            os.unlink(tmp_path)


# ── Chat / Plan refinement ────────────────────────────────────────────────────

class ChatMessage(BaseModel):
    role: str   # "user" | "assistant"
    content: str

class ChatRequest(BaseModel):
    anamnesis: dict  # free-form dict — no strict validation needed for chat context
    original_analysis: str
    messages: List[ChatMessage]  # full conversation history incl. latest user message

class ChatResponse(BaseModel):
    reply: str
    tokens_remaining: Optional[float] = None


CHAT_SYSTEM_PROMPT = """Eres la IA Analítica by Teo Mariscal, una inteligencia artificial especializada en conducta canina, \
creada para ayudar a etólogos y adiestradores a refinar planes de modificación de conducta.

Ya has realizado un Análisis Funcional ABC completo de este caso. Ahora el profesional quiere profundizar, \
corregir algún dato o pedir alternativas a pasos del plan que no son viables en la situación real del cliente.

Tu misión:
- Escuchar las aclaraciones o restricciones del profesional.
- Ajustar o completar el plan de intervención con esa nueva información.
- Ofrecer alternativas concretas, basadas en evidencia, cuando alguna recomendación original no sea aplicable.
- Mantener siempre un tono clínico, profesional y directo.
- No repetir el análisis completo salvo que te lo pidan expresamente; céntrate en la parte que hay que revisar.
- Si el profesional dice algo como "los perros viven juntos y no pueden separarse", propón protocolos de \
  convivencia y desensibilización que funcionen en esa restricción, sin volver a recomendar la separación.
- IMPORTANTE: No uses nunca markdown. Nada de ##, ###, **, *, `, — decorativo ni ningún símbolo de formato. \
  Escribe texto limpio con párrafos separados por saltos de línea. Para listas usa guión simple seguido de espacio.

Responde en español. Sé conciso y útil."""


@router.post("/chat", response_model=ChatResponse)
def analysis_chat(
    req: ChatRequest,
    authorization: Optional[str] = Header(None),
    db: Session = Depends(get_db),
):
    """
    Refinement chat — 0.25 tokens per exchange.

    Accepts the original anamnesis, the full analysis text, and the
    accumulated conversation history. Returns the AI's next reply.
    """
    tokens_left = deduct_token(authorization, db, amount=0.25)

    from app.core.anthropic_client import get_anthropic_client

    # Build context block with anamnesis + original analysis
    context = (
        f"=== FICHA DEL CASO ===\n{json.dumps(req.anamnesis, ensure_ascii=False, indent=2)}\n\n"
        f"=== ANÁLISIS ABC ORIGINAL ===\n{req.original_analysis}"
    )

    # Convert conversation history to Anthropic format
    messages = []
    # First turn: inject context as a user message followed by an ack so history is clean
    messages.append({
        "role": "user",
        "content": f"Aquí tienes el contexto completo del caso que ya analizaste:\n\n{context}",
    })
    messages.append({
        "role": "assistant",
        "content": "Entendido. Tengo el caso completo y el análisis previo. ¿En qué parte del plan quieres que trabajemos?",
    })
    # Append real conversation
    for m in req.messages:
        messages.append({"role": m.role, "content": m.content})

    client = get_anthropic_client()
    try:
        response = client.messages.create(
            model="claude-sonnet-4-5",        # Sonnet 4.5 — fast & high quality for chat
            max_tokens=1024,
            system=CHAT_SYSTEM_PROMPT,
            messages=messages,
        )
        reply = _strip_markdown(response.content[0].text)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error de IA: {e}")

    return ChatResponse(reply=reply, tokens_remaining=tokens_left)
