import json
import os
import tempfile

from fastapi import APIRouter, File, Form, HTTPException, UploadFile

from app.models.anamnesis import AnamnesisInput, AnalysisResponse
from app.services.clinical_ai import run_clinical_analysis

router = APIRouter(prefix="/analysis", tags=["clinical-analysis"])

# Max video size accepted: 200 MB
MAX_VIDEO_BYTES = 200 * 1024 * 1024

ALLOWED_VIDEO_TYPES = {
    "video/mp4", "video/quicktime", "video/x-msvideo",
    "video/x-matroska", "video/webm", "video/mpeg",
}


@router.post("", response_model=AnalysisResponse)
def create_analysis(anamnesis: AnamnesisInput):
    """
    Run a Functional Behavioral Analysis (text-only anamnesis).

    Accepts the full anamnesis form, retrieves relevant knowledge from
    Qdrant, and returns a clinical ABC analysis generated by Claude
    Sonnet 4.6 with prompt caching active on the system prompt.
    """
    try:
        return run_clinical_analysis(anamnesis)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/video", response_model=AnalysisResponse)
async def create_analysis_with_video(
    anamnesis_json: str = Form(..., description="Full AnamnesisInput serialised as JSON"),
    video: UploadFile = File(..., description="Video of the dog's behavior (MP4, MOV, AVI…)"),
):
    """
    Run a Functional Behavioral Analysis with an attached video.

    The video is stored to a temporary file, key frames are extracted
    with OpenCV (or ffmpeg as fallback), and the frames are passed to
    Claude alongside the written anamnesis for multi-modal analysis.
    """
    # ── Validate content type ────────────────────────────────────────────────
    ct = (video.content_type or "").lower()
    if ct and ct not in ALLOWED_VIDEO_TYPES:
        raise HTTPException(
            status_code=415,
            detail=f"Unsupported video format: {ct}. Use MP4, MOV, AVI or MKV.",
        )

    # ── Read & size-check the upload ─────────────────────────────────────────
    video_bytes = await video.read()
    if len(video_bytes) > MAX_VIDEO_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"Video too large ({len(video_bytes) // 1024 // 1024} MB). Max 200 MB.",
        )

    # ── Parse anamnesis ──────────────────────────────────────────────────────
    try:
        anamnesis_data = json.loads(anamnesis_json)
        anamnesis = AnamnesisInput(**anamnesis_data)
    except Exception as e:
        raise HTTPException(status_code=422, detail=f"Invalid anamnesis JSON: {e}")

    # ── Write video to temp file & extract frames ────────────────────────────
    suffix = os.path.splitext(video.filename or "video.mp4")[1] or ".mp4"
    tmp_path = None
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            tmp.write(video_bytes)
            tmp_path = tmp.name

        from app.services.video_processor import extract_frames
        try:
            frames = extract_frames(tmp_path)
        except RuntimeError as e:
            # Frame extraction failed — fall back to text-only analysis
            frames = []
            import logging
            logging.getLogger(__name__).warning(
                "Frame extraction failed, falling back to text-only: %s", e
            )

        return run_clinical_analysis(anamnesis, video_frames=frames or None)

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if tmp_path and os.path.exists(tmp_path):
            os.unlink(tmp_path)
