from fastapi import APIRouter, HTTPException
from app.models.intervention import InterventionRequest, InterventionResponse
from app.services.intervention_ai import run_intervention_plan

router = APIRouter(prefix="/intervention", tags=["intervention-plan"])


@router.post("", response_model=InterventionResponse)
def create_intervention(request: InterventionRequest):
    """
    Generate a LIMA-based behavioral intervention plan.

    Accepts the full anamnesis + the FBA analysis text and returns a
    structured 3-phase intervention plan generated by Claude Sonnet 4.6.
    """
    try:
        return run_intervention_plan(request)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
