from typing import Optional
from fastapi import APIRouter, HTTPException, Header, Depends, Query
from sqlalchemy.orm import Session

from app.models.intervention import InterventionRequest, InterventionResponse
from app.services.intervention_ai import run_intervention_plan
from app.database import get_db
from app.core.case_persistence import persist_to_case_safely, get_user_from_authorization
from app.config import get_settings

router = APIRouter(prefix="/intervention", tags=["intervention-plan"])


@router.post("", response_model=InterventionResponse)
def create_intervention(
    request: InterventionRequest,
    case_id: Optional[str] = Query(None, description="Si se pasa, persiste el plan como entry del caso"),
    authorization: Optional[str] = Header(None),
    db: Session = Depends(get_db),
):
    """
    Generate a LIMA-based behavioral intervention plan.

    Accepts the full anamnesis + the FBA analysis text and returns a
    structured 3-phase intervention plan generated by Claude Sonnet 4.6.
    Si se pasa case_id como query, persiste el plan como entry tipo
    'intervention' en el caso (no rompe la respuesta si la persistencia falla).
    """
    try:
        result = run_intervention_plan(request)
        # Persistencia opcional al caso
        if case_id:
            user = get_user_from_authorization(authorization, db)
            persist_to_case_safely(
                case_id, user, db,
                entry_type="intervention",
                content=getattr(result, "plan", None) or "",
                meta={"endpoint": "/intervention"},
                ai_model=get_settings().clinical_model,
                input_tokens=getattr(result, "input_tokens", None),
                output_tokens=getattr(result, "output_tokens", None),
                update_summary_plan=True,
            )
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
